# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=16, null=True)),
                ('summery', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to=b'./carousel/image/%Y/%m/%d/')),
                ('target_url', models.URLField(blank=True, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('show_order', models.IntegerField(default=0)),
                ('on_show', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['show_order', '-create_time'],
                'verbose_name': '\u8f6e\u64ad',
                'verbose_name_plural': '\u8f6e\u64ad',
            },
        ),
    ]
