# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 16:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('student_id', models.CharField(max_length=16)),
                ('college', models.CharField(max_length=16)),
                ('tel', models.CharField(max_length=11)),
                ('is_public_tel', models.BooleanField(default=False)),
                ('sex', models.CharField(choices=[(b'M', '\u7537'), (b'F', '\u5973')], max_length=1)),
                ('level', models.SmallIntegerField()),
                ('birthday', models.DateField()),
                ('qq', models.CharField(max_length=32)),
                ('is_public_qq', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(upload_to=b'./user/photo/%Y/%m/%d/')),
                ('is_publisher', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
